before:
  hooks:
    - dep ensure -vendor-only
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli/pflags/main.go
    binary: pflags
    goos:
      - linux
      - windows
      - darwin
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
scoop:
  # Template for the url.
  # Default is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  # url_template: "http://github.mycompany.com/foo/bar/releases/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  bucket:
    owner: lyft
    name: flytestdlib

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Your app's homepage.
  # Default is empty.
  homepage: "https://godoc.org/github.com/lyft/flytestdlib"

  # Your app's description.
  # Default is empty.
  description: "Common Go utilities (Typed-Config, PFlags, Prometheus Metrics,... more)."

  # Your app's license
  # Default is empty.
  license: Apache-2.0

  # Persist data between application updates
  persist:
  - "data"
  - "config.toml"