sudo: required
language: go
go:
  - "1.11"
jobs:
  include:
    - stage: test
      name: unit tests
      install: make install
      script: make test_unit
    - stage: test
      name: benchmark tests
      install: make install
      script: make test_benchmark
    - stage: test
      install: make install
      name: lint
      script: make lint
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
